# Generated by Django 4.2 on 2023-04-24 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercicio', models.CharField(max_length=255)),
                ('video', models.FileField(upload_to='videos/')),
                ('tutorial', models.TextField(max_length=500)),
                ('time', models.PositiveIntegerField()),
                ('dia_semana', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='academia.dias')),
            ],
        ),
    ]
