# Generated by Django 4.2.3 on 2023-07-10 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videos',
            name='tutorial',
        ),
        migrations.AlterField(
            model_name='videos',
            name='time',
            field=models.CharField(max_length=255),
        ),
    ]
