# Generated by Django 4.2.3 on 2023-07-12 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0002_remove_videos_tutorial_alter_videos_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='quantidade',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videos',
            name='repeticao',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='videos',
            name='time',
            field=models.IntegerField(default=0),
        ),
    ]
