# Generated by Django 4.2.3 on 2023-07-12 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0003_videos_quantidade_videos_repeticao_alter_videos_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='quantidade',
            field=models.PositiveIntegerField(max_length=255),
        ),
        migrations.AlterField(
            model_name='videos',
            name='time',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
