# Generated by Django 4.2.3 on 2023-07-13 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0004_alter_videos_quantidade_alter_videos_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='quantidade',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
