# Generated by Django 4.2.3 on 2023-07-13 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0005_alter_videos_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='video',
            field=models.CharField(max_length=255),
        ),
    ]
