# Generated by Django 4.2.3 on 2023-08-01 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academia', '0006_alter_videos_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreinoDIa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='academia.dias')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='videos',
            name='dia_semana',
        ),
        migrations.CreateModel(
            name='VideoDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academia.treinodia')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academia.videos')),
            ],
        ),
    ]
