# Generated by Django 4.2.3 on 2023-08-01 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0007_treinodia_remove_videos_dia_semana_videodia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videodia',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academia.videos', unique=True),
        ),
    ]
