# Generated by Django 4.2.3 on 2023-08-01 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0011_alter_videodia_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videodia',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academia.videos'),
        ),
    ]
