# Generated by Django 4.2.3 on 2023-08-01 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academia', '0012_alter_videodia_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videodia',
            name='treino',
        ),
        migrations.AddField(
            model_name='videodia',
            name='dia',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='academia.dias'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videodia',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TreinoDIa',
        ),
    ]
