# Generated by Django 4.2.3 on 2023-08-01 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0013_remove_videodia_treino_videodia_dia_videodia_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videodia',
            name='dia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academia.dias'),
        ),
    ]
