# Generated by Django 4.2.3 on 2023-08-01 12:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academia', '0014_alter_videodia_dia'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VideoDia',
            new_name='TreinoDia',
        ),
    ]
