# Generated by Django 4.2.3 on 2023-08-08 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0015_rename_videodia_treinodia'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='id_video_youtube',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
