# Generated by Django 4.2.3 on 2023-08-08 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0016_videos_id_video_youtube'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='id_video_youtube',
            field=models.CharField(default=1, max_length=50),
        ),
    ]
