# Generated by Django 4.2.3 on 2023-08-21 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0017_alter_videos_id_video_youtube'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='categorias',
            field=models.CharField(choices=[('GLU', 'Glúteos'), ('PER', 'PERNAS'), ('GLU', 'Glúteos'), ('1', 'Nenhum')], default='1', max_length=5),
        ),
    ]
