# Generated by Django 4.2.3 on 2023-08-22 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0018_categoriamodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='categorias',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academia.categoriamodel'),
        ),
    ]
