# Generated by Django 4.2.3 on 2023-08-22 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0019_videos_categorias'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='info',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
