# Generated by Django 4.2.3 on 2023-08-22 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0020_videos_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='info',
            field=models.CharField(default='...', max_length=255, null=True),
        ),
    ]
