# Generated by Django 4.2.3 on 2023-08-27 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0021_alter_videos_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videos',
            name='categorias',
        ),
        migrations.AddField(
            model_name='videos',
            name='categorias',
            field=models.ManyToManyField(to='academia.categoriamodel'),
        ),
    ]
