# Generated by Django 4.2.3 on 2023-09-26 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academia', '0022_remove_videos_categorias_userdiaslista_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TreinoDia',
            new_name='TreinoDiaPadrao',
        ),
        migrations.CreateModel(
            name='TreinoDiaUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academia.userdiaslista')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academia.videos')),
            ],
        ),
    ]
