# Generated by Django 4.2.3 on 2023-09-26 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academia', '0023_rename_treinodia_treinodiapadrao_videos_categorias_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemLista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.CharField(max_length=255)),
                ('treinodia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academia.userdiaslista')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
