# Generated by Django 4.2.3 on 2023-09-27 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0024_videos_categorias_ordemlista'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='id_video_youtube_didatico',
            field=models.CharField(default=1, max_length=50),
        ),
        migrations.AddField(
            model_name='videos',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
