# Generated by Django 4.2.3 on 2023-10-03 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0025_videos_categorias_videos_id_video_youtube_didatico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemlista',
            name='treinodiapadrao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academia.dias'),
        ),
    ]
