# Generated by Django 4.2.3 on 2023-10-03 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0026_ordemlista_treinodiapadrao_videos_categorias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemlista',
            name='treinodia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academia.userdiaslista'),
        ),
    ]
