# Generated by Django 4.2.3 on 2023-10-13 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0027_videos_categorias_alter_ordemlista_treinodia'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='categorias',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='academia.categoriamodel'),
        ),
    ]
