# Generated by Django 4.2.3 on 2023-11-13 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0028_videos_categorias'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipamentoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipamento', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='videos',
            name='equipamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='academia.equipamentomodel'),
        ),
    ]
