# Generated by Django 4.2.3 on 2023-11-20 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0029_equipamentomodel_videos_equipamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
