# Generated by Django 4.2.3 on 2023-12-01 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0031_alter_videos_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='categorias',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
