# Generated by Django 4.2.3 on 2023-12-01 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0032_alter_videos_categorias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='categorias',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='academia.categoriamodel'),
        ),
    ]
