from decouple import config


# DEBUG
DEBUG_VAR = config('DEBUG_VAR')

# EMAIL
EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
EMAIL_USE_TLS = config('EMAIL_USE_TLS')
EMAIL_PORT = config('EMAIL_PORT')
EMAIL_HOST = config('EMAIL_HOST')
SECRET_KEY = config('SECRET_KEY')
RECAPTCHA_PRIVATE_KEY = config ('RECAPTCHA_PRIVATE_KEY')


# AWS S3 STORAGE
AWS_ACCESS_KEY_ID = config('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = config('AWS_SECRET_ACCESS_KEY')
AWS_STORAGE_BUCKET_NAME = config('AWS_STORAGE_BUCKET_NAME')


# REDIS
REDIS_PASSAWORD = config('REDIS_PASSAWORD')
REDIS_URL = config('REDIS_URL')


# DATABASE
ENGINE_DATABASE = config('ENGINE_DATABASE', default='')
USER_DATABASE = config('USER_DATABASE', default='')
PASSWORD_DATABASE = config('PASSWORD_DATABASE', default='')
HOST_DATABASE = config('HOST_DATABASE', default='')
NAME_DATABASE = config('NAME_DATABASE', default='')
PORT_DATABASE = config('PORT_DATABASE', default='')
